Fix BadgeSummaryAction.appendText() API compatibility issue
The appendText() method no longer accepts a boolean parameter in the
newer version of the badge plugin. This was causing build failures with:
MissingMethodException: No signature of method:
BadgeSummaryAction.appendText() is applicable for argument types:
(java.lang.String, java.lang.Boolean)

Solution:
- Removed the boolean parameter from all appendText() calls
- Changed appendText(..., false) to appendText(...) in 3 locations:
  * Line 1005: RELEASE PUBLISH BINARIES header
  * Line 1007: NIGHTLY PUBLISH BINARIES header
  * Line 1275: closing </ul> tag

This fixes the Jenkins build failures in the publish stage.